server:
  port: 8080

spring:
  rabbitmq:
    host: 106.14.205.253
    port: 5672
    virtual-host: /dev
    password: 224336
    username: admin
    #开启消息二次确认: 生产者到broker的交换机
    publisher-confirm-type: correlated
    #开启消息二次确认: 交换机到队列的可靠性投递
    publisher-returns: true
    #修改交换机投递的策略 true表示交换机处理消息失败则会返回给生产者
    template:
      mandatory: true
    #消息手工确认ACK 消费完成不会自动ack 控制台会消息状态会变成unacked
    listener:
      simple:
        acknowledge-mode: manual
